# __An Introduction to the Julia Programming Language__

<br>

__Finance 5330: Financial Econometrics__ <br>
Tyler J. Brough <br>
Created:      January 10, 2020 <br>
Last Updated: January 28, 2020 <br>
<br>

## Nota Bene

* These notes are based on Chapter 1 of the book _Introduction to Quantitative Macroeconomics Using Julia_ by Petre Caraiani (in Files & Media database on Notion).


* An additional resource that you will want to check out is the [Quantitative Economics with Julia](https://julia.quantecon.org/index_toc.html) lecture notes. 

* The official [Julia Documentation](https://docs.julialang.org/en/v1/) is also very detailed and of high quality. 

## Overview

* Julia is a new general purpose programming language that is focused on numerical and statistical computing. Its development began at MIT in 2009. In 2018 it reached a stable 1.0 release. 


* From Caraiani: _"The main attractiveness of the [sic] Julia comes from combining the high level syntax of languages like Python and Matlab with the speed of low level languages like Fortran and C/C++."_ It is said that Julia solves the two language problem. See [this article (https://www.nature.com/articles/d41586-019-02310-3) at Nature for more details. 


Here is how the Julia design team position their language. See the language website: https://julialang.org/

### Julia is fast!

Julia was designed from the beginning for high performance. Julia programs compile to efficient native code for multiple platforms via LLVM.


### Dynamic

Julia is dynamically-typed, feels like a scripting language, and has good support for interactive use.


### Optionally typed

Julia has a rich language of descriptive datatypes, and type declarations can be used to clarify and solidify programs.


In [5]:
x = 1

1

In [4]:
varinfo()

| name |    size | summary |
|:---- | -------:|:------- |
| Base |         | Module  |
| Core |         | Module  |
| Main |         | Module  |
| x    | 8 bytes | Int64   |


### General

Julia uses multiple dispatch as a paradigm, making it easy to express many object-oriented and functional programming patterns. It provides asynchronous I/O, debugging, logging, profiling, a package manager, and more.


### Easy to use

Julia has high level syntax, making it an accessible language for programmers from any background or experience level. Browse the Julia microbenchmarks to get a feel for the language.


### Open source

Julia is provided under the MIT license, free for everyone to use. All source code is publicly viewable on GitHub.


<br>

## Julia in a Nutshell

### Installing Julia

* To install Julia go to the [Julia downloads page](https://julialang.org/downloads/) and make the proper selection for your operating system (Windows or Mac OS - if you're on Linux I'm just going to assume you're okay on your own).

* As of the time of writing this most current version of Julia is v1.3.1. Make sure that you get at least this version. 


#### Installing Anaconda

I also strongly suggest that you install the Anaconda system. 

* Go to the [Anaconda downloads page](https://www.anaconda.com/distribution/) and make the proper selection for your operating system (again either Windows or Mac OS). 

* Make sure to get at least v3.7 of Python. 

* This will give us Jupyter Lab and an installation of Python to work with from Julia. 


#### Text Editors

You will want to choose a good text editor. 

* If you don't have a strong preference then use Jupyter Lab. I'll be demonstrating this in class.


* Julia comes bundled with a text editor called Juno, which is based off of Atom. It's pretty good. It's the straight forward editor to use if you don't know how to choose. 


* [Microsoft Visual Studio Code](https://code.visualstudio.com/) offers a good combination of simplicity and power.


* I really like [Neovim](https://neovim.io/). Vim gives you super powers but has a steep learning curve. 
    - Learning Vim was an intellectual lightning strike for me!


* [Emacs](https://www.gnu.org/software/emacs/) is nutso powerful and has a nearly infinite learning curve. Extra credit for the Brave and True!
    - See what writer Neal Stephenson has to say about Emacs: https://www.emacswiki.org/emacs/NealStephenson
    

* Of course, Buddha who always advocated the [Middle Way](https://en.wikipedia.org/wiki/Middle_Way) would use [Doom](https://github.com/hlissner/doom-emacs) if he were alive today!
    - Doom is Emacs with a builtin Vim emulator. It's the *Shiz* - is what I think the kids say these days!
    - See these YouTube videos if you decide to follow this path: https://www.youtube.com/watch?v=rCMh7srOqvw


<br>

See here for the [QuantEcon install instructions](https://julia.quantecon.org/getting_started_julia/getting_started.html). Note that these may or may not be up-to-date.

<br>

### Julia Packages

Once Julia is installed we can use the Standard Library, which is the set of functions and data structures that come builtin to Julia. Similar to other programming languages such as Python and R, Julia is an extensible language. This means that we can write code to extend Julia's base capabilities. 

Julia comes with a builtin package manager called `Pkg`. We can use it to install any Julia package. For example, to add the `stats` package, we can do the following: 

In [6]:
using Pkg
Pkg.add("Distributions")

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 % Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.3/Manifest.toml`
 [no changes]


To start this package at the REPL, we can write:

In [7]:
using Distributions

┌ Info: Precompiling Distributions [31c24e10-a181-5473-b8eb-7969acd0382f]
└ @ Base loading.jl:1273


Packages can be updated with the command: `Pkg.update()`

In [8]:
Pkg.update()


  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.3/Manifest.toml`
 [no changes]


### Understanding the REPL

REPL stands for Read-Evaluate-Print-Loop. When we start up Julia we are presented with the REPL. This is the most direct and powerful way to interact with Julia. 

To use the REPL, we type commands directly in and press enter to immediately execute the code. Here is an example:

In [4]:
x = 1

1

What we're doing here is assigning the value `0` to the variable `x`. 

We can access the builtin help as follows:

In [5]:
?

search: ⊻ ⊋ ⊊ ⊉ ⊈ ⊇ ⊆ ≥ ≤ ≢ ≡ ≠ ≉ ≈ ∪ ∩ ∛ √ ∘ ∌ ∋ ∉ ∈ ℯ π ÷ ~ | ^ \ > < : / - +



**Welcome to Julia 1.3.0.** The full manual is available at

```
https://docs.julialang.org/
```

as well as many great tutorials and learning resources:

```
https://julialang.org/learning/
```

For help on a specific function or macro, type `?` followed by its name, e.g. `?cos`, or `?@time`, and press enter. Type `;` to enter shell mode, `]` to enter package mode.


In [9]:
?sum

search: sum sum! summary cumsum cumsum! isnumeric MethodSummary EdgeworthSum



```
sum(f, itr)
```

Sum the results of calling function `f` on each element of `itr`.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

# Examples

```jldoctest
julia> sum(abs2, [2; 3; 4])
29
```

Note the important difference between `sum(A)` and `reduce(+, A)` for arrays with small integer eltype:

```jldoctest
julia> sum(Int8[100, 28])
128

julia> reduce(+, Int8[100, 28])
-128
```

In the former case, the integers are widened to system word size and therefore the result is 128. In the latter case, no such widening happens and integer overflow results in -128.

---

```
sum(itr)
```

Returns the sum of all elements in a collection.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

# Examples

```jldoctest
julia> sum(1:20)
210
```

---

```
sum(A::AbstractArray; dims)
```

Sum elements of an array over the given dimensions.

# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> sum(A, dims=1)
1×2 Array{Int64,2}:
 4  6

julia> sum(A, dims=2)
2×1 Array{Int64,2}:
 3
 7
```


### Variables and Operators

In this section we will cover Julia's main syntax. 


* One of Julia's key features is that it is a ___typed___ language

* This means that the programmer can choose the type of variables or the types of arguments to a function that represent data

* Julia can infer the type of a variable from the way it is initialized, for example: 

In [1]:
x = 1

1

In [2]:
## It's an Int64
typeof(x)

Int64

* Julia understands that this is an _integer_ type 

* In addition, Julia is a ___dynamically-typed___ language. That means that even after it is declared it can be assigned to a new type of data. 

In [3]:
x = "Hello, World!"

"Hello, World!"

In [4]:
## Now it's a String
typeof(x)

String

#### Integers

* There are two basic types of integers: 1) signed and 2) unsigned

* The signed integer types are: `Int8`, `Int32`, `Int64`, and `Int128`

* The unsiqned integer types are: `UInt8`, `UInt32`, `UInt64`, and `UInt128`

* Julia also has a `BigInt` type for when there is a need for high precision outside the range allowed above the types of integers. 

* When we try to store an integer data type outside of the allowed range, say $[-128, 127]$ for `Int8`, we will get overflow (or underflow)

* Julia does not up-cast these automatically, so care is needed in working with your data. 

In [9]:
local w::Int8 = 128

InexactError: InexactError: trunc(Int8, 128)

In [13]:
local w::Int32 = 129

129

In [10]:
local w::Int8 = 120

120

In [11]:
w = 130

130

In [12]:
typeof(w)

Int64

#### Booleans

* Julia has a type `Bool`.


* The `Bool` type is used for logical variables that take the values `true` or `false`

In [13]:
x = (1 > 0)

true

In [14]:
typeof(x)

Bool

In [16]:
Int(x)

1

#### Floating Point Numbers

* Julia includes a second primative numeric type to represent decimal numbers


* These are called ___floating point numbers___


* These are the workhorse types for most of computational science (including finance and econometrics) 


* (__NB:__ Julia also allows you to create your very own ___primatives___)


* Here are the basic floating point types: `Float16`, `Float32` (also called _single precision_), `Float64` (also called _double precision_)


* For a very high level of precision, Julia has the type `BigFloat` 


* Of course, there is a trade-off between precision and performance. 


* For most of our work, we will use `Float64` to represent our financial and economic data (though sometimes we may prefer even `Float32` for performance reasons)



In [17]:
local x::Float32 = 3.14
local y::Float64 = 3.14

3.14

#### Complex Numbers


* Julia supports complex numbers through its `Complex` type


* It builds off of the primative numeric types


In [18]:
c = 2 + 3im

2 + 3im

In [19]:
typeof(c)

Complex{Int64}

In [20]:
c = complex(2, 3)

2 + 3im

In [21]:
typeof(c)

Complex{Int64}

#### Strings

* Julia has a `String` type to represent character data


* Strings are a succession (or arrays) of characters in Julia


* Before we go further with Strings, we first need to discuss characters


In [22]:
y = 'y'

'y': ASCII/Unicode U+0079 (category Ll: Letter, lowercase)

In [23]:
typeof(y)

Char

* Basically, a `Char` stands for a single character 


* There is a numeric value assigned to each `Char` value


* We can find it with the `Int()` function: 

In [24]:
Int(y)

121

* We can initiate a `String` with either double or triple quotes

In [25]:
str = "Hello"

"Hello"

In [26]:
typeof(str)

String

* We can subset the String to get a single character

In [31]:
str[1]

'H': ASCII/Unicode U+0048 (category Lu: Letter, uppercase)

In [32]:
typeof(str[1])

Char

* __NB:__ One thing to keep in mind (especially if coming from `C++`, `Java`, or `Python`) is that indexing in Julia starts at 1

In [33]:
jike = str[2:3]

"el"

In [34]:
typeof(jike)

String

### Operators

#### Arithmetic Operators

* Julia supports the standard arithmetic operators

In [35]:
## Addition is what you would think
4 + 5

9

In [36]:
## So is subtraction
5 - 4

1

In [37]:
## Use an asterisk for multiplication
2 * 3

6

In [40]:
## Use a slash for division
4/2

2.0

#### Comparison Operators


* We can apply the usual comparison operators, i.e. equality, inequality, less than, greater than for all types of primatives in Julia. 


* Their use is rather intuitive

In [41]:
## Notice the double equal signs
5 == 5

true

In [42]:
5 == 6

false

In [43]:
5 != 6

true

In [44]:
5 > 6

false

In [45]:
5 < 6

true

#### Updating Operators


* We can update the value of any variable using ___updating operators___. 


* Just at the `=` sign to the usual arithmetic operator


* The result is the operation done on the left-hand side operand 

In [46]:
x = 2

2

In [48]:
x += 4

10

#### Mathematical Functions

* Julia makes scientific computing a first class citizen in the language and as a result comes with a host of mathematical functions baked right in

* 

In [49]:
round(1.2)

1.0

In [50]:
sqrt(9)

3.0

In [51]:
exp(3)

20.085536923187668

In [52]:
log(10)

2.302585092994046

 * Trigonometric, hyperbolic, and other special functions are also well covered. See the documentation for more information.

### Vectors

* Julia has very powerful array types built-in

* The type for a one-dimensional array or vector is `Array{Type,N}(dims)` type `Type` stands for the type of the data, while `N` stands for the length of the vector, which is determined by `dims`. 


* There are different ways to create vectors in Julia

In [53]:
v = Array{Float32, 3}

Array{Float32,3}

In [54]:
show(v)

Array{Float32,3}

* It's better to do it this way though

In [55]:
v = Float32[]

0-element Array{Float32,1}

* There are alternative ways to create vectors which can be very useful in doing computational work

In [56]:
v1 = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [58]:
v1[4] = 6

6

In [60]:
v1

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 6.0
 0.0

In [61]:
v2 = ones(5)

5-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0

* We can use the `range` function to create sequences

In [62]:
?range

search: range LinRange UnitRange StepRange StepRangeLen trailing_zeros



```
range(start[, stop]; length, stop, step=1)
```

Given a starting value, construct a range either by length or from `start` to `stop`, optionally with a given step (defaults to 1, a [`UnitRange`](@ref)). One of `length` or `stop` is required.  If `length`, `stop`, and `step` are all specified, they must agree.

If `length` and `stop` are provided and `step` is not, the step size will be computed automatically such that there are `length` linearly spaced elements in the range (a [`LinRange`](@ref)).

If `step` and `stop` are provided and `length` is not, the overall range length will be computed automatically such that the elements are `step` spaced (a [`StepRange`](@ref)).

`stop` may be specified as either a positional or keyword argument.

!!! compat "Julia 1.1"
    `stop` as a positional argument requires at least Julia 1.1.


# Examples

```jldoctest
julia> range(1, length=100)
1:100

julia> range(1, stop=100)
1:100

julia> range(1, step=5, length=100)
1:5:496

julia> range(1, step=5, stop=100)
1:5:96

julia> range(1, 10, length=101)
1.0:0.09:10.0

julia> range(1, 100, step=5)
1:5:96
```


In [63]:
v2 = range(1, stop=5, step=2)

1:2:5

In [64]:
typeof(v2)

StepRange{Int64,Int64}

In [65]:
collect(v2)

3-element Array{Int64,1}:
 1
 3
 5

* We can use built-in pseudo-random number generators (PRNGs)

In [66]:
v = rand(20)

20-element Array{Float64,1}:
 0.9410164248349369  
 0.6507732625612082  
 0.21514112111449224 
 0.6514199483706984  
 0.8582894874736429  
 0.3006682683672719  
 0.4997208292588673  
 0.12917841005792186 
 0.7311433113530597  
 0.5870616563634272  
 0.17771155611377631 
 0.19973064031141585 
 0.9278230450964009  
 0.42018855478603245 
 0.5279864781507477  
 0.04299950541109432 
 0.6686805365083646  
 0.96438965955203    
 0.004636930206813883
 0.8490152818535281  

In [67]:
randn(10)

10-element Array{Float64,1}:
 -0.1946458579352076  
  3.2164892529272926  
 -0.2258021545859412  
  0.3473738902077344  
  0.046135741233781724
 -0.33274639763465513 
  0.9261046904004453  
  0.006489972147602601
  0.012178284737620905
  0.33958744994791645 

In [70]:
typeof(v)

Array{Float64,1}

* Julia has some simple yet powerful functions to help when working with arrays/vectors. 


* We can concatenate two vectors using the function `append`

In [76]:
v1 = zeros(2)
v2 = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [77]:
## Notice the bang !
append!(v1, v2)

5-element Array{Float64,1}:
 0.0
 0.0
 1.0
 1.0
 1.0

In [78]:
## The result is appended to v1
v1

5-element Array{Float64,1}:
 0.0
 0.0
 1.0
 1.0
 1.0

### Multidimensional Arrays


* 

### Functions

### Control Flow

### Working with Data

### Working with Dates

### Data Frames

### Plotting with Julia

## Advanced Features

### Julia's Type System

### Multiple Dispatch

### Vectorization

## References