# __An Introduction to the Julia Programming Language__

<br>

__Finance 5330: Financial Econometrics__ <br>
Tyler J. Brough <br>
Created:      January 10, 2020 <br>
Last Updated: January 23, 2020 <br>
<br>

## Nota Bene

* These notes are based on Chapter 1 of the book _Introduction to Quantitative Macroeconomics Using Julia_ by Petre Caraiani (in Files & Media database on Notion).


* An additional resource that you will want to check out is the [Quantitative Economics with Julia](https://julia.quantecon.org/index_toc.html) lecture notes. 

* The official [Julia Documentation](https://docs.julialang.org/en/v1/) is also very detailed and of high quality. 

## Overview

* Julia is a new general purpose programming language that is focused on numerical and statistical computing. Its development began at MIT in 2009. In 2018 it reached a stable 1.0 release. 


* From Caraiani: _"The main attractiveness of the [sic] Julia comes from combining the high level syntax of languages like Python and Matlab with the speed of low level languages like Fortran and C/C++."_ It is said that Julia solves the two language problem. See [this article (https://www.nature.com/articles/d41586-019-02310-3) at Nature for more details. 


Here is how the Julia design team position their language. See the language website: https://julialang.org/

### Julia is fast!

Julia was designed from the beginning for high performance. Julia programs compile to efficient native code for multiple platforms via LLVM.


### Dynamic

Julia is dynamically-typed, feels like a scripting language, and has good support for interactive use.


### Optionally typed

Julia has a rich language of descriptive datatypes, and type declarations can be used to clarify and solidify programs.


### General

Julia uses multiple dispatch as a paradigm, making it easy to express many object-oriented and functional programming patterns. It provides asynchronous I/O, debugging, logging, profiling, a package manager, and more.


### Easy to use

Julia has high level syntax, making it an accessible language for programmers from any background or experience level. Browse the Julia microbenchmarks to get a feel for the language.


### Open source

Julia is provided under the MIT license, free for everyone to use. All source code is publicly viewable on GitHub.


<br>

## Julia in a Nutshell

### Installing Julia

* To install Julia go to the [Julia downloads page](https://julialang.org/downloads/) and make the proper selection for your operating system (Windows or Mac OS - if you're on Linux I'm just going to assume you're okay on your own).

* As of the time of writing this most current version of Julia is v1.3.1. Make sure that you get at least this version. 


#### Installing Anaconda

I also strongly suggest that you install the Anaconda system. 

* Go to the [Anaconda downloads page](https://www.anaconda.com/distribution/) and make the proper selection for your operating system (again either Windows or Mac OS). 

* Make sure to get at least v3.7 of Python. 

* This will give us Jupyter Lab and an installation of Python to work with from Julia. 


#### Text Editors

You will want to choose a good text editor. 

* If you don't have a strong preference then use Jupyter Lab. I'll be demonstrating this in class.


* Julia comes bundled with a text editor called Juno, which is based off of Atom. It's pretty good. It's the straight forward editor to use if you don't know how to choose. 


* [Microsoft Visual Studio Code](https://code.visualstudio.com/) offers a good combination of simplicity and power.


* I really like [Neovim](https://neovim.io/). Vim gives you super powers but has a steep learning curve. 
    - Learning Vim was an intellectual lightning strike for me!


* [Emacs](https://www.gnu.org/software/emacs/) is nutso powerful and has a nearly infinite learning curve. Extra credit for the Brave and True!
    - See what writer Neal Stephenson has to say about Emacs: https://www.emacswiki.org/emacs/NealStephenson
    

* Of course, Buddha who always advocated the [Middle Way](https://en.wikipedia.org/wiki/Middle_Way) would use [Doom](https://github.com/hlissner/doom-emacs) if he were alive today!
    - Doom is Emacs with a builtin Vim emulator. It's the *Shiz* - is what I think the kids say these days!
    - See these YouTube videos if you decide to follow this path: https://www.youtube.com/watch?v=rCMh7srOqvw


<br>

See here for the [QuantEcon install instructions](https://julia.quantecon.org/getting_started_julia/getting_started.html). Note that these may or may not be up-to-date.

<br>

### Julia Packages

Once Julia is installed we can use the Standard Library, which is the set of functions and data structures that come builtin to Julia. Similar to other programming languages such as Python and R, Julia is an extensible language. This means that we can write code to extend Julia's base capabilities. 

Julia comes with a builtin package manager called `Pkg`. We can use it to install any Julia package. For example, to add the `stats` package, we can do the following: 

In [1]:
using Pkg
Pkg.add("Distributions")

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 %========>                                ]  18.3 %Fetching: [==========>                              ]  24.8 %>                      ]  42.9 % [=========================>               ]  61.2 %>        ]  78.5 %=======================================> ]  96.8 % Resolving package versions...
 Installed PDMats ─ v0.9.11
  Updating `~/.julia/environments/v1.3/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [90014a1f] ↑ PDMats v0.9.10 ⇒ v0.9.11


To start this package at the REPL, we can write:

In [2]:
using Distributions

┌ Info: Precompiling Distributions [31c24e10-a181-5473-b8eb-7969acd0382f]
└ @ Base loading.jl:1273


Packages can be updated with the command: `Pkg.update()`

In [3]:
Pkg.update()

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.3/Manifest.toml`
 [no changes]


### Understanding the REPL

REPL stands for Read-Evaluate-Print-Loop. When we start up Julia we are presented with the REPL. This is the most direct and powerful way to interact with Julia. 

To use the REPL, we type commands directly in and press enter to immediately execute the code. Here is an example:

In [4]:
x = 1

1

What we're doing here is assigning the value `0` to the variable `x`. 

We can access the builtin help as follows:

In [5]:
?

search: ⊻ ⊋ ⊊ ⊉ ⊈ ⊇ ⊆ ≥ ≤ ≢ ≡ ≠ ≉ ≈ ∪ ∩ ∛ √ ∘ ∌ ∋ ∉ ∈ ℯ π ÷ ~ | ^ \ > < : / - +



**Welcome to Julia 1.3.0.** The full manual is available at

```
https://docs.julialang.org/
```

as well as many great tutorials and learning resources:

```
https://julialang.org/learning/
```

For help on a specific function or macro, type `?` followed by its name, e.g. `?cos`, or `?@time`, and press enter. Type `;` to enter shell mode, `]` to enter package mode.


In [7]:
?sum

search: sum sum! summary cumsum cumsum! isnumeric MethodSummary EdgeworthSum



```
sum(f, itr)
```

Sum the results of calling function `f` on each element of `itr`.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

# Examples

```jldoctest
julia> sum(abs2, [2; 3; 4])
29
```

Note the important difference between `sum(A)` and `reduce(+, A)` for arrays with small integer eltype:

```jldoctest
julia> sum(Int8[100, 28])
128

julia> reduce(+, Int8[100, 28])
-128
```

In the former case, the integers are widened to system word size and therefore the result is 128. In the latter case, no such widening happens and integer overflow results in -128.

---

```
sum(itr)
```

Returns the sum of all elements in a collection.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

# Examples

```jldoctest
julia> sum(1:20)
210
```

---

```
sum(A::AbstractArray; dims)
```

Sum elements of an array over the given dimensions.

# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> sum(A, dims=1)
1×2 Array{Int64,2}:
 4  6

julia> sum(A, dims=2)
2×1 Array{Int64,2}:
 3
 7
```


### Variables and Operators

In this section we will cover Julia's main syntax. 

### Vectors

### Multidimensional Arrays

### Functions

### Control Flow

### Working with Data

### Working with Dates

### Data Frames

### Plotting with Julia

## Advanced Features

### Julia's Type System

### Multiple Dispatch

### Vectorization

## References