# __Monte Carlo Simulation for OLS Regression__

<br>

In [1]:
using Random
using StatsKit
using StatsPlots

### __Step 1: Design the True/Unknown Data-Generating Process__

In [32]:
n = 1000
X = rand(n, 2);

In [51]:
X[1:end,1] .= 1.0;

In [4]:
X[1:10,:]

10×2 Array{Float64,2}:
 1.0  0.538925
 1.0  0.88668
 1.0  0.647537
 1.0  0.299307
 1.0  0.507355
 1.0  0.86984
 1.0  0.320553
 1.0  0.218794
 1.0  0.263566
 1.0  0.181531

### __Step 1 - Part A__

<br>

Select the true parameter values

<br>

So our regression equation will become:

$$
y_{i} = \alpha + \beta X_{i} + \varepsilon_{i}
$$

<br>

In [5]:
β = [0.98, 2.34]

2-element Array{Float64,1}:
 0.98
 2.34

In [6]:
u = 0.1 * randn(n);
y = X * β + u;      # suppress output

In [7]:
betahat = llsq(X, y; bias=false)

2-element Array{Float64,1}:
 0.9832234590168893
 2.340104357664927

### __Step 2: Run a Sampling Theory Simulation__

In [46]:
m = 1_000_000

1000000

In [47]:
betahat = zeros(m);

In [48]:
for i in 1:m
    ε = 0.1 * randn(n);                # the error-term is the sort-of stochastic driver
    y = X * β + ε;                     # the data-generating process ("population")
    betatmp = llsq(X, y; bias=false);  # run the OLS regression (via optimization)
    betahat[i] = betatmp[2]            # we want the slope coefficient estimate
end

In [52]:
(round(mean(betahat); digits=3), round(std(betahat); digits=3))

(2.34, 0.011)